### ISSUE TITLE
 cannot load such file -- httparty (LoadError)

### ISSUE THREAD

**Issue by happy199** [Flutterwave/Ruby#3]
Hi. I have another problem. I think that it in your sdk.

In lib/flutterwave_sdk.rb you user HTTPARTY, but it generate error on my site.

hera is console error, 

Traceback (most recent call last):
        26: from bin/rails:9:in `<main>'
        25: from bin/rails:9:in `require'
        24: from C:/Users/atidjani/Ruby25/lib/ruby/gems/2.5.0/gems/railties-5.2.8.1/lib/rails/commands.rb:18:in `<top (required)>'
        23: from C:/Users/atidjani/Ruby25/lib/ruby/gems/2.5.0/gems/railties-5.2.8.1/lib/rails/command.rb:46:in `invoke'
        22: from C:/Users/atidjani/Ruby25/lib/ruby/gems/2.5.0/gems/railties-5.2.8.1/lib/rails/command/base.rb:69:in `perform'
        21: from C:/Users/atidjani/Ruby25/lib/ruby/gems/2.5.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        20: from C:/Users/atidjani/Ruby25/lib/ruby/gems/2.5.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        19: from C:/Users/atidjani/Ruby25/lib/ruby/gems/2.5.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        18: from C:/Users/atidjani/Ruby25/lib/ruby/gems/2.5.0/gems/railties-5.2.8.1/lib/rails/commands/server/server_command.rb:142:in `perform'
        17: from C:/Users/atidjani/Ruby25/lib/ruby/gems/2.5.0/gems/railties-5.2.8.1/lib/rails/commands/server/server_command.rb:142:in `tap'
        16: from C:/Users/atidjani/Ruby25/lib/ruby/gems/2.5.0/gems/railties-5.2.8.1/lib/rails/commands/server/server_command.rb:145:in `block in perform'
        15: from C:/Users/atidjani/Ruby25/lib/ruby/gems/2.5.0/gems/railties-5.2.8.1/lib/rails/commands/server/server_command.rb:145:in `require'
        14: from C:/wamp64/www/sewema-app/config/application.rb:9:in `<top (required)>'
        13: from C:/Users/atidjani/Ruby25/lib/ruby/gems/2.5.0/gems/bundler-2.3.22/lib/bundler.rb:187:in `require'
        12: from C:/Users/atidjani/Ruby25/lib/ruby/gems/2.5.0/gems/bundler-2.3.22/lib/bundler/runtime.rb:44:in `require'
        11: from C:/Users/atidjani/Ruby25/lib/ruby/gems/2.5.0/gems/bundler-2.3.22/lib/bundler/runtime.rb:44:in `each'
        10: from C:/Users/atidjani/Ruby25/lib/ruby/gems/2.5.0/gems/bundler-2.3.22/lib/bundler/runtime.rb:55:in `block in require'
         9: from C:/Users/atidjani/Ruby25/lib/ruby/gems/2.5.0/gems/bundler-2.3.22/lib/bundler/runtime.rb:55:in `each'
         8: from C:/Users/atidjani/Ruby25/lib/ruby/gems/2.5.0/gems/bundler-2.3.22/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
         7: from C:/Users/atidjani/Ruby25/lib/ruby/gems/2.5.0/gems/bundler-2.3.22/lib/bundler/runtime.rb:60:in `require'
         6: from C:/Users/atidjani/Ruby25/lib/ruby/gems/2.5.0/gems/flutterwave_sdk-0.1.1/lib/flutterwave_sdk.rb:3:in `<top (required)>'
         5: from C:/Users/atidjani/Ruby25/lib/ruby/gems/2.5.0/gems/flutterwave_sdk-0.1.1/lib/flutterwave_sdk.rb:3:in `require_relative'
         4: from C:/Users/atidjani/Ruby25/lib/ruby/gems/2.5.0/gems/flutterwave_sdk-0.1.1/lib/flutterwave_sdk/flutterwave_objects/base/base.rb:1:in `<top (required)>'
         3: from C:/Users/atidjani/Ruby25/lib/ruby/gems/2.5.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
         2: from C:/Users/atidjani/Ruby25/lib/ruby/gems/2.5.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
         1: from C:/Users/atidjani/Ruby25/lib/ruby/gems/2.5.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
C:/Users/atidjani/Ruby25/lib/ruby/gems/2.5.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require': cannot load such file -- httparty (LoadError)

So it not able to load httparty.

I don't know why. Can you help me please ?

**Comment by mofeejegi** [comment]
I'm not sure why this happens in the first place, but you can simply include `gem 'httparty'` in your `Gemfile` and then run `bundle install`. 

That stops this issue from occurring.
